workflows:
  ios-workflow:
    name: iOS Build

    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Create files
        script: |
          mkdir -p build/ios/ipa
          echo "fake ipa" > build/ios/ipa/Dopamine.ipa

    artifacts:
      - build/ios/ipa/*.ipa
