workflows:
  ios-workflow:
    name: iOS Build

    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Build app
        script: |
          xcodebuild \
          -project DopamineApp.xcodeproj \
          -scheme DopamineApp \
          -sdk iphoneos \
          -configuration Release \
          build

    artifacts:
      - build/ios/ipa/*.ipa
